"use client";

import React, { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Sparkles, Wand2, FileText, Globe, Palette, Check, ArrowRight, HelpCircle, AlertCircle } from "lucide-react";
import { useUIStore } from "@/stores/ui-store";
import { cn } from "@/lib/utils";

interface FormOption {
  id: string;
  title: string;
  slug: string;
}

export default function AIBuilderPage() {
  const router = useRouter();
  const user = useUIStore((state) => state.user);

  // Active tab: "form" or "landing"
  const [activeTab, setActiveTab] = useState<"form" | "landing">("form");
  const [prompt, setPrompt] = useState("");
  const [brandColor, setBrandColor] = useState<"emerald" | "amber" | "ocean" | "purple">("emerald");
  const [enableLandingPage, setEnableLandingPage] = useState(true);
  const [connectedFormSlug, setConnectedFormSlug] = useState("");
  const [forms, setForms] = useState<FormOption[]>([]);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Fetch user forms to connect to landing page
  useEffect(() => {
    async function fetchForms() {
      try {
        const res = await fetch("/api/forms");
        if (res.ok) {
          const data = await res.json();
          // Filter forms out of landing page types
          const standardForms = data.forms
            .filter((f: any) => {
              const s = typeof f.settings === "string" ? JSON.parse(f.settings) : f.settings || {};
              return !s.isLandingPage;
            })
            .map((f: any) => ({
              id: f.id,
              title: f.title,
              slug: f.slug,
            }));
          setForms(standardForms);
          if (standardForms.length > 0) {
            setConnectedFormSlug(standardForms[0].slug);
          }
        }
      } catch (err) {
        console.error("Failed to load forms:", err);
      }
    }
    fetchForms();
  }, []);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;

    setGenerating(true);
    setError(null);

    try {
      if (activeTab === "form") {
        // Generate Form
        const res = await fetch("/api/ai/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt }),
        });

        if (!res.ok) {
          throw new Error("Failed to generate form schema from AI.");
        }

        const data = await res.json();

        // Apply brand color and custom configs
        const payload = {
          title: data.title || "AI Generated Form",
          description: data.description || "Generated by ANSH AI Assistant",
          fields: data.fields || [],
          landingPage: {
            ...(data.landingPage || {}),
            enabled: enableLandingPage,
          },
          settings: {
            ...(data.settings || {}),
            brandColor: brandColor,
          },
        };

        // Create the form record
        const formRes = await fetch("/api/forms", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        });

        if (!formRes.ok) {
          throw new Error("Failed to save the generated form.");
        }

        const formData = await formRes.json();
        router.push(`/forms/${formData.form.id}/edit`);
      } else {
        // Generate Landing Page
        if (!connectedFormSlug) {
          throw new Error("Please connect a form database first.");
        }

        const res = await fetch("/api/ai/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt, isLandingPage: true }),
        });

        if (!res.ok) {
          throw new Error("Failed to generate landing page content from AI.");
        }

        const data = await res.json();

        const payload = {
          title: data.title || "AI Generated Landing Page",
          description: `Landing Page connected to /f/${connectedFormSlug}`,
          fields: [], // landing pages do not contain questions directly
          landingPage: {
            enabled: true,
            heroTitle: data.title || "Premium Launch Portal",
            heroSubtitle: data.description || "Learn more and register details below.",
            connectedFormSlug: connectedFormSlug,
            faqs: data.landingPage?.faqs || [
              { question: "How does this template work?", answer: "This section answers core visitor questions instantly." }
            ],
            contactEmail: user?.email || "support@anshapps.com",
            contactPhone: "",
          },
          settings: {
            isLandingPage: true,
            brandColor: brandColor,
            thankYouTitle: "Registration Received!",
            thankYouMessage: "We have secured your registration successfully.",
          },
        };

        const saveRes = await fetch("/api/forms", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        });

        if (!saveRes.ok) {
          throw new Error("Failed to save the generated landing page.");
        }

        const formData = await saveRes.json();
        router.push(`/forms/${formData.form.id}/edit`);
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || "An unexpected error occurred during generation.");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-fadeIn">
      {/* Title Header */}
      <div className="select-none text-left">
        <h1 className="text-2xl font-black text-slate-800 dark:text-zinc-100 tracking-tight leading-tight flex items-center gap-2">
          <Sparkles className="h-6 w-6 text-primary animate-pulse" />
          <span>AI Copilot Builder</span>
        </h1>
        <p className="text-xs text-slate-400 dark:text-slate-500 font-semibold mt-1">
          Instruct our intelligent agent to compile fields, structured question stages, FAQ matrices, and branding colors.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {/* Settings & Guide Panel */}
        <div className="md:col-span-1 space-y-6">
          {/* Tabs */}
          <div className="crm-card bg-card border-border overflow-hidden p-1.5 flex flex-col gap-1 select-none">
            <button
              type="button"
              onClick={() => {
                setActiveTab("form");
                setError(null);
              }}
              className={cn(
                "w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-xs font-bold uppercase tracking-wider text-left transition-all cursor-pointer",
                activeTab === "form"
                  ? "bg-primary text-primary-foreground shadow-sm"
                  : "text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"
              )}
            >
              <FileText className="h-4.5 w-4.5" />
              <span>Generate Form</span>
            </button>
            <button
              type="button"
              onClick={() => {
                setActiveTab("landing");
                setError(null);
              }}
              className={cn(
                "w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-xs font-bold uppercase tracking-wider text-left transition-all cursor-pointer",
                activeTab === "landing"
                  ? "bg-primary text-primary-foreground shadow-sm"
                  : "text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"
              )}
            >
              <Globe className="h-4.5 w-4.5" />
              <span>Generate Landing Page</span>
            </button>
          </div>

          {/* Quick Examples */}
          <div className="crm-card bg-card border-border p-5 space-y-4">
            <h3 className="text-[10px] font-black uppercase text-slate-400 tracking-wider flex items-center gap-1.5 select-none">
              <HelpCircle className="h-4 w-4 text-primary" />
              <span>Prompt Examples</span>
            </h3>
            <div className="space-y-2.5 text-xs text-slate-500 dark:text-slate-400 font-medium">
              {activeTab === "form" ? (
                <>
                  <button
                    onClick={() => setPrompt("Create a school admission form with student details, date of birth, parent phone, grade level select, and previous school history.")}
                    className="w-full text-left p-2.5 rounded-lg border border-border/60 hover:border-primary/55 bg-slate-50/50 dark:bg-slate-900/30 hover:bg-card text-[11px] leading-relaxed transition-colors cursor-pointer"
                  >
                    &ldquo;Create a school admission form...&rdquo;
                  </button>
                  <button
                    onClick={() => setPrompt("Build a customer feedback survey capturing rating stars, signature check, recommendation checkboxes, and standard user email.")}
                    className="w-full text-left p-2.5 rounded-lg border border-border/60 hover:border-primary/55 bg-slate-50/50 dark:bg-slate-900/30 hover:bg-card text-[11px] leading-relaxed transition-colors cursor-pointer"
                  >
                    &ldquo;Build a customer feedback survey...&rdquo;
                  </button>
                </>
              ) : (
                <>
                  <button
                    onClick={() => setPrompt("Create a premium landing page for college admissions. Highlight our green campus, student events, and placement cell statistics.")}
                    className="w-full text-left p-2.5 rounded-lg border border-border/60 hover:border-primary/55 bg-slate-50/50 dark:bg-slate-900/30 hover:bg-card text-[11px] leading-relaxed transition-colors cursor-pointer"
                  >
                    &ldquo;Create a landing page for college admissions...&rdquo;
                  </button>
                  <button
                    onClick={() => setPrompt("Generate a registration launch page for a local Hackathon with contact phone, developer details, FAQs, and accent banner images.")}
                    className="w-full text-left p-2.5 rounded-lg border border-border/60 hover:border-primary/55 bg-slate-50/50 dark:bg-slate-900/30 hover:bg-card text-[11px] leading-relaxed transition-colors cursor-pointer"
                  >
                    &ldquo;Generate a registration launch page...&rdquo;
                  </button>
                </>
              )}
            </div>
          </div>
        </div>

        {/* Builder Interactive Screen */}
        <div className="md:col-span-2">
          <form onSubmit={handleGenerate} className="crm-card bg-card border-border p-6 space-y-6 relative overflow-hidden">
            {generating && (
              <div className="absolute inset-0 bg-card/85 backdrop-blur-[2px] z-20 flex flex-col items-center justify-center text-center p-6 animate-fadeIn">
                <div className="relative flex items-center justify-center mb-4">
                  <div className="h-14 w-14 border-4 border-primary/20 border-t-primary rounded-full animate-spin" />
                  <Sparkles className="h-6 w-6 text-primary absolute animate-pulse" />
                </div>
                <h3 className="text-sm font-bold text-slate-800 dark:text-zinc-100">AI Prompt Agent Active</h3>
                <p className="text-xs text-slate-400 mt-1 max-w-xs leading-relaxed">
                  Synthesizing JSON fields model structure, cover accents, auto-generating FAQs accordion content, and saving structure...
                </p>
                <div className="w-48 bg-border h-1 rounded-full overflow-hidden mt-4">
                  <div className="bg-primary h-full rounded-full animate-[shimmer_1.5s_infinite]" style={{ width: "60%" }} />
                </div>
              </div>
            )}

            <div className="space-y-2">
              <label className="text-[10px] font-black uppercase text-slate-400 dark:text-slate-500 tracking-wider block">
                Describe your requirements in detail
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder={
                  activeTab === "form"
                    ? "e.g. Create a job application form for a senior software developer. Request resume file uploads, linkedin profile link, phone number, and a rating of React experience."
                    : "e.g. Create a developer summit landing page. Include sections explaining registration, FAQ on tickets pricing, contact address, and hero call to actions."
                }
                className="w-full h-36 p-4 rounded-2xl border border-border text-xs font-semibold outline-none focus:border-primary/50 text-slate-800 dark:text-zinc-200 bg-slate-50/30 dark:bg-slate-900/10 focus:bg-card resize-none leading-relaxed"
                required
              />
            </div>

            {error && (
              <div className="bg-rose-500/10 border border-rose-500/20 text-rose-500 p-3.5 rounded-xl flex items-start gap-2.5 text-xs font-semibold">
                <AlertCircle className="h-4.5 w-4.5 shrink-0 mt-0.5" />
                <span>{error}</span>
              </div>
            )}

            {/* Custom Brand Preferences */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5 border-t border-border/40 pt-5">
              <div className="space-y-2 select-none">
                <label className="text-[10px] font-black uppercase text-slate-400 dark:text-slate-500 tracking-wider flex items-center gap-1">
                  <Palette className="h-4 w-4" />
                  <span>Choose Brand Theme Accent</span>
                </label>
                <div className="grid grid-cols-4 gap-2">
                  {[
                    { id: "emerald", label: "Teal", color: "bg-emerald-500" },
                    { id: "amber", label: "Amber", color: "bg-amber-500" },
                    { id: "ocean", label: "Sky", color: "bg-sky-500" },
                    { id: "purple", label: "Purple", color: "bg-purple-500" },
                  ].map((color) => (
                    <button
                      key={color.id}
                      type="button"
                      onClick={() => setBrandColor(color.id as any)}
                      className={cn(
                        "flex flex-col items-center gap-1.5 p-2 rounded-xl border transition-all cursor-pointer",
                        brandColor === color.id
                          ? "border-primary bg-primary/5 dark:bg-primary/10 shadow-sm"
                          : "border-border/60 hover:bg-slate-50 dark:hover:bg-slate-800"
                      )}
                    >
                      <span className={cn("h-4 w-4 rounded-full shadow-inner", color.color)} />
                      <span className="text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400">
                        {color.label}
                      </span>
                    </button>
                  ))}
                </div>
              </div>

              {activeTab === "form" ? (
                <div className="flex flex-col justify-center">
                  <label className="flex items-center gap-2.5 p-3 rounded-2xl border border-border/60 bg-slate-50/30 dark:bg-slate-900/10 cursor-pointer select-none">
                    <input
                      type="checkbox"
                      checked={enableLandingPage}
                      onChange={(e) => setEnableLandingPage(e.target.checked)}
                      className="accent-primary h-4.5 w-4.5"
                    />
                    <div className="text-left">
                      <span className="text-xs font-bold text-slate-700 dark:text-zinc-300 block">
                        Auto Generate Landing Page
                      </span>
                      <span className="text-[9px] font-semibold text-slate-400 block mt-0.5">
                        Compiles a hero banner and FAQ accordion with your form.
                      </span>
                    </div>
                  </label>
                </div>
              ) : (
                <div className="space-y-2 text-left">
                  <label className="text-[10px] font-black uppercase text-slate-400 dark:text-slate-500 tracking-wider block">
                    Connect Form Database
                  </label>
                  {forms.length === 0 ? (
                    <div className="text-[10px] text-rose-500 font-bold p-3 rounded-xl border border-rose-500/20 bg-rose-500/5">
                      No standard forms found. Please create a Form first before building a Landing Page!
                    </div>
                  ) : (
                    <select
                      value={connectedFormSlug}
                      onChange={(e) => setConnectedFormSlug(e.target.value)}
                      className="premium-input text-xs font-semibold focus:border-primary/50"
                      required
                    >
                      {forms.map((f) => (
                        <option key={f.id} value={f.slug}>
                          {f.title} (/f/{f.slug})
                        </option>
                      ))}
                    </select>
                  )}
                </div>
              )}
            </div>

            {/* Submission Actions */}
            <div className="flex justify-end pt-2 border-t border-border/40">
              <button
                type="submit"
                disabled={generating || !prompt.trim() || (activeTab === "landing" && forms.length === 0)}
                className="flex items-center gap-2 px-5 py-3 rounded-xl bg-primary text-primary-foreground font-black text-xs uppercase tracking-wider shadow-md shadow-primary/20 hover:scale-[1.02] active:scale-95 disabled:opacity-50 cursor-pointer duration-200"
              >
                <Wand2 className="h-4.5 w-4.5" />
                <span>{generating ? "Generating Plan..." : "Run AI Generator"}</span>
                <ArrowRight className="h-3.5 w-3.5 ml-1" />
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
